[toolchain]
anchor_version = "1.2.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_pay = "5pY9AH8qYE6u17MYknPeoy9HufpguEAt9Lj1vnoXqzNC"

[programs.devnet]
escrow_pay = "5pY9AH8qYE6u17MYknPeoy9HufpguEAt9Lj1vnoXqzNC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
